-- MySQL Script generated by MySQL Workbench
-- Thu Sep 20 14:26:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbapicola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbapicola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbapicola` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `dbapicola` ;

-- -----------------------------------------------------
-- Table `dbapicola`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbapicola`.`sector` (
  `idsector` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `rcto` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `observacion` LONGTEXT NOT NULL,
  `responsable` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idsector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbapicola`.`colmena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbapicola`.`colmena` (
  `idcolmena` INT NOT NULL AUTO_INCREMENT,
  `idarea` INT NOT NULL,
  `nmarcos` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nalza` INT NOT NULL,
  `origen` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `idreina` INT NOT NULL,
  `fechareina` DATE NOT NULL,
  PRIMARY KEY (`idcolmena`),
  INDEX `fk_colmena_sector_idx` (`idarea` ASC) VISIBLE,
  CONSTRAINT `fk_colmena_sector`
    FOREIGN KEY (`idarea`)
    REFERENCES `dbapicola`.`sector` (`idsector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbapicola`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbapicola`.`division` (
  `iddivision` INT NOT NULL AUTO_INCREMENT,
  `idcolmena` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`iddivision`),
  INDEX `fk_division_colmena_idx` (`idcolmena` ASC) VISIBLE,
  CONSTRAINT `fk_division_colmena`
    FOREIGN KEY (`idcolmena`)
    REFERENCES `dbapicola`.`colmena` (`idcolmena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbapicola`.`captura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbapicola`.`captura` (
  `idcaptura` INT NOT NULL AUTO_INCREMENT,
  `idcolmena` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idcaptura`),
  INDEX `fk_captura_colmena_idx` (`idcolmena` ASC) VISIBLE,
  CONSTRAINT `fk_captura_colmena`
    FOREIGN KEY (`idcolmena`)
    REFERENCES `dbapicola`.`colmena` (`idcolmena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbapicola`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbapicola`.`compra` (
  `idcompra` INT NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `idcolmena` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compra_colmena_idx` (`idcolmena` ASC) VISIBLE,
  CONSTRAINT `fk_compra_colmena`
    FOREIGN KEY (`idcolmena`)
    REFERENCES `dbapicola`.`colmena` (`idcolmena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbapicola`.`mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbapicola`.`mantenimiento` (
  `idmantenimiento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `idobrero` INT NOT NULL,
  `idcolmena` INT NOT NULL,
  `alimentacion` TINYINT NOT NULL,
  PRIMARY KEY (`idmantenimiento`),
  INDEX `fk_mantenimiento_colmena_idx` (`idcolmena` ASC) VISIBLE,
  CONSTRAINT `fk_mantenimiento_colmena`
    FOREIGN KEY (`idcolmena`)
    REFERENCES `dbapicola`.`colmena` (`idcolmena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbapicola`.`cosecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbapicola`.`cosecha` (
  `idcosecha` INT NOT NULL AUTO_INCREMENT,
  `idcolmena` INT NOT NULL,
  `idobrero` INT NOT NULL,
  `marcos` INT NOT NULL,
  `pesovacio` VARCHAR(45) NOT NULL,
  `pesolleno` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `tipoalza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcosecha`),
  INDEX `fk_cosecha_colmena_idx` (`idcolmena` ASC) VISIBLE,
  CONSTRAINT `fk_cosecha_colmena`
    FOREIGN KEY (`idcolmena`)
    REFERENCES `dbapicola`.`colmena` (`idcolmena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
